### ISSUE TITLE
Update for VS2022

### ISSUE THREAD

**Issue by dgnuff** [Sebazzz/VsRemovePublishButton#3]
Title pretty much says it all.  Is it on your roadmap to update this to work with VS 2022?

**Comment by Sebazzz** [comment]
If there is demand for it, I don't mind trying! 💯

**Comment by ronan-fesselier** [comment]
There is demand :)

**Comment by Sebazzz** [comment]
Thanks for the subtle reminder @333fps - I'm checking out which changes I need to do for VS2022 🙃

**Comment by ronan-fesselier** [comment]
So nice :) I never tried tweaking visual until now. It's something I should learn.

**Comment by Sebazzz** [comment]
VS2022 support soon available [via the Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=Sebazzz.RemovetheVisualStudioPublishbutton), otherwise downloadable already now via [the release page](https://github.com/Sebazzz/VsRemovePublishButton/releases/tag/v1.5).

Thanks for the support!

**Comment by ronan-fesselier** [comment]
"The extension cannot be installed on this product due to prerequisites that cannot be resolved" (VS Community 17.2.1)  I'll check the sources later on. Thanks a lot !

**Comment by Sebazzz** [comment]
Apologies - update released a v1.6!
